import type { Finding, Opportunity, Initiative, DashboardKPIs } from './types'

export const mockKPIs: DashboardKPIs = {
  total_clicks: 14820,
  clicks_delta: -12.3,
  total_impressions: 284600,
  impressions_delta: -8.7,
  avg_ctr: 5.21,
  ctr_delta: -0.4,
  avg_position: 8.4,
  position_delta: -1.2,
  findings_count: 18,
  critical_findings: 3,
  opportunities_count: 7,
  roadmap_items: 12,
}

export const mockFindings: Finding[] = [
  {
    id: 'f1',
    site_id: 'site1',
    category: 'visibility',
    severity: 'high',
    title: 'Chute de −34% de clics sur les requêtes "blog canin"',
    description: 'Le cluster de requêtes "blog canin" a perdu 34% de clics en 28 jours. Les impressions restent stables, suggérant une chute de position et de CTR.',
    asset_type: 'topic',
    metric_value: -34,
    metric_label: 'Δ clics 28j',
    created_at: '2025-07-10T08:00:00Z',
    is_dismissed: false,
    evidence: [
      { id: 'e1', finding_id: 'f1', source: 'gsc', label: 'Clics J-28', value: 1240, date: '2025-07-10' },
      { id: 'e2', finding_id: 'f1', source: 'gsc', label: 'Clics actuel', value: 818, date: '2025-07-10' },
    ],
  },
  {
    id: 'f2',
    site_id: 'site1',
    category: 'visibility',
    severity: 'medium',
    title: 'Aucune impression sur le topic "nutrition chien senior"',
    description: 'Le topic "nutrition chien senior" représente un volume de recherche estimé à 8 400 requêtes/mois mais génère 0 impression pour le domaine.',
    asset_type: 'topic',
    metric_value: 0,
    metric_label: 'Impressions',
    created_at: '2025-07-08T10:00:00Z',
    is_dismissed: false,
  },
  {
    id: 'f3',
    site_id: 'site1',
    category: 'visibility',
    severity: 'medium',
    title: 'Position moyenne en hausse sur les requêtes longue traîne',
    description: '42 requêtes longue traîne ont vu leur position moyenne augmenter de +3.2 points, impactant le CTR global.',
    asset_type: 'query',
    metric_value: 3.2,
    metric_label: 'Δ position',
    created_at: '2025-07-09T09:00:00Z',
    is_dismissed: false,
  },
  {
    id: 'f4',
    site_id: 'site1',
    category: 'serp',
    severity: 'high',
    title: 'Concurrent DogFood.be capte 78% des top 3 sur vos requêtes cibles',
    description: 'Sur un échantillon de 24 requêtes prioritaires, DogFood.be occupe la position 1 à 3 dans 78% des cas, contre 12% pour votre domaine.',
    asset_type: 'domain',
    metric_value: 78,
    metric_label: '% top 3 concurrent',
    created_at: '2025-07-11T08:00:00Z',
    is_dismissed: false,
    evidence: [
      { id: 'e3', finding_id: 'f4', source: 'serp', label: 'Snapshots analysés', value: 24, date: '2025-07-11' },
    ],
  },
  {
    id: 'f5',
    site_id: 'site1',
    category: 'serp',
    severity: 'medium',
    title: 'Présence marque absente sur 12 requêtes navigationnelles',
    description: '12 requêtes incluant votre nom de marque ou des variantes proches ne retournent pas votre domaine en top 5.',
    asset_type: 'query',
    metric_value: 12,
    metric_label: 'Requêtes sans présence',
    created_at: '2025-07-09T11:00:00Z',
    is_dismissed: false,
  },
  {
    id: 'f6',
    site_id: 'site1',
    category: 'ai_search',
    severity: 'high',
    title: 'Domaine absent des AI Overviews sur 8 requêtes prioritaires',
    description: 'Sur 8 requêtes à fort volume pour lesquelles un AI Overview est déclenché, votre domaine n\'est jamais cité comme source.',
    asset_type: 'query',
    metric_value: 0,
    metric_label: 'Citations AI Overview',
    created_at: '2025-07-11T14:00:00Z',
    is_dismissed: false,
    evidence: [
      { id: 'e4', finding_id: 'f6', source: 'ai_overview', label: 'AIO détectés', value: 8, date: '2025-07-11' },
      { id: 'e5', finding_id: 'f6', source: 'ai_overview', label: 'Citations domaine', value: 0, date: '2025-07-11' },
    ],
  },
  {
    id: 'f7',
    site_id: 'site1',
    category: 'ai_search',
    severity: 'medium',
    title: 'Petfood.nl cité 5× plus souvent dans les AI Overviews',
    description: 'Sur l\'ensemble des AI Overviews détectés, Petfood.nl est cité en source 5 fois plus fréquemment que votre domaine.',
    asset_type: 'domain',
    metric_value: 5,
    metric_label: 'Ratio citations concurrent',
    created_at: '2025-07-11T14:30:00Z',
    is_dismissed: false,
  },
  {
    id: 'f8',
    site_id: 'site1',
    category: 'pages',
    severity: 'high',
    title: '/blog/alimentation-chiot sous-performe (CTR 0.8% vs moy. 3.2%)',
    description: 'La page /blog/alimentation-chiot génère 12 000 impressions mais seulement 96 clics. Son CTR de 0.8% est 4× inférieur à la moyenne du site.',
    asset_type: 'page',
    asset_url: '/blog/alimentation-chiot',
    metric_value: 0.8,
    metric_label: 'CTR actuel',
    created_at: '2025-07-10T09:00:00Z',
    is_dismissed: false,
    evidence: [
      { id: 'e6', finding_id: 'f8', source: 'gsc', label: 'Impressions', value: 12000 },
      { id: 'e7', finding_id: 'f8', source: 'gsc', label: 'Clics', value: 96 },
      { id: 'e8', finding_id: 'f8', source: 'gsc', label: 'CTR moyen site', value: '3.2%' },
    ],
  },
  {
    id: 'f9',
    site_id: 'site1',
    category: 'pages',
    severity: 'medium',
    title: 'Page /nourriture-senior linkée mais hors top 50 sur ses requêtes cibles',
    description: 'Cette page reçoit des liens internes depuis 12 pages mais n\'apparaît pas dans les 50 premiers résultats pour ses 6 requêtes cibles.',
    asset_type: 'page',
    asset_url: '/nourriture-senior',
    created_at: '2025-07-08T15:00:00Z',
    is_dismissed: false,
  },
  {
    id: 'f10',
    site_id: 'site1',
    category: 'indexation',
    severity: 'critical',
    title: 'Page /chien-age canonicalisée vers une URL inexistante',
    description: 'La balise canonical de /chien-age pointe vers /chien-senior qui retourne une 404. Google signale la page comme non indexée.',
    asset_type: 'page',
    asset_url: '/chien-age',
    created_at: '2025-07-11T08:30:00Z',
    is_dismissed: false,
    evidence: [
      { id: 'e9', finding_id: 'f10', source: 'url_inspection', label: 'Statut Google', value: 'Not indexed' },
      { id: 'e10', finding_id: 'f10', source: 'url_inspection', label: 'Canonical URL', value: '/chien-senior (404)' },
    ],
  },
  {
    id: 'f11',
    site_id: 'site1',
    category: 'indexation',
    severity: 'high',
    title: '3 pages stratégiques avec statut "Discovered but not indexed"',
    description: 'Google a découvert 3 pages stratégiques de la section produits mais ne les a pas indexées. Elles ne reçoivent aucun lien interne.',
    asset_type: 'page',
    metric_value: 3,
    metric_label: 'Pages non indexées',
    created_at: '2025-07-09T16:00:00Z',
    is_dismissed: false,
  },
]

export const mockOpportunities: Opportunity[] = [
  {
    id: 'o1',
    site_id: 'site1',
    type: 'expand_coverage',
    title: 'Renforcer la couverture topique "nutrition senior"',
    description: 'Le topic "nutrition chien senior" représente un potentiel non capté. Créer un cluster de contenu autour de cette thématique permettrait de capter une audience ciblée à haute intention.',
    status: 'accepted',
    finding_ids: ['f2', 'f9'],
    impact_score: 4,
    effort_score: 3,
    confidence_score: 4,
    created_at: '2025-07-11T10:00:00Z',
  },
  {
    id: 'o2',
    site_id: 'site1',
    type: 'fix_technical',
    title: 'Corriger les blocages d\'indexation sur les pages stratégiques',
    description: 'Un canonical cassé et 3 pages non indexées limitent la couverture crawl et l\'autorité transmise aux pages clés. Fix prioritaire avant toute action de contenu.',
    status: 'accepted',
    finding_ids: ['f10', 'f11'],
    impact_score: 5,
    effort_score: 2,
    confidence_score: 5,
    created_at: '2025-07-11T11:00:00Z',
  },
  {
    id: 'o3',
    site_id: 'site1',
    type: 'refresh_content',
    title: 'Optimiser le CTR des pages blog à fort volume',
    description: 'Plusieurs pages blog génèrent de fortes impressions mais un CTR très faible. Une révision des titres, métas et structure peut significativement augmenter les clics sans créer de nouveau contenu.',
    status: 'accepted',
    finding_ids: ['f8'],
    impact_score: 3,
    effort_score: 2,
    confidence_score: 4,
    created_at: '2025-07-10T14:00:00Z',
  },
  {
    id: 'o4',
    site_id: 'site1',
    type: 'strengthen_ai',
    title: 'Construire l\'autorité AI Search via contenu citatoire',
    description: 'L\'absence dans les AI Overviews est liée à un manque de contenu structuré, factuel et citable. Produire des pages répondant aux formats E-E-A-T augmentera les chances de citation.',
    status: 'proposed',
    finding_ids: ['f6', 'f7'],
    impact_score: 4,
    effort_score: 4,
    confidence_score: 3,
    created_at: '2025-07-11T15:00:00Z',
  },
  {
    id: 'o5',
    site_id: 'site1',
    type: 'defend_competitor',
    title: 'Défendre les requêtes capturées par DogFood.be',
    description: 'Sur 24 requêtes prioritaires, DogFood.be domine le top 3. Identifier les pages concurrentes et renforcer les pages correspondantes avec du contenu de meilleure qualité.',
    status: 'proposed',
    finding_ids: ['f4'],
    impact_score: 4,
    effort_score: 4,
    confidence_score: 3,
    created_at: '2025-07-11T12:00:00Z',
  },
  {
    id: 'o6',
    site_id: 'site1',
    type: 'reinforce_authority',
    title: 'Renforcer l\'autorité entité marque dans les SERP',
    description: 'La présence de la marque est faible sur les requêtes navigationnelles. Optimiser les pages clés (About, Homepage) et le Knowledge Panel peut corriger cela.',
    status: 'proposed',
    finding_ids: ['f5'],
    impact_score: 3,
    effort_score: 2,
    confidence_score: 3,
    created_at: '2025-07-09T16:00:00Z',
  },
]

export const mockInitiatives: Initiative[] = [
  {
    id: 'i1',
    workspace_id: 'ws1',
    opportunity_id: 'o2',
    type: 'core_fix',
    title: 'Corriger le canonical cassé sur /chien-age',
    description: 'Mettre à jour la balise canonical pour pointer vers l\'URL correcte /chien-age-senior.',
    why_this_matters: 'Une page stratégique est actuellement non indexée à cause d\'un canonical pointant vers une 404. Fix rapide avec impact immédiat sur la couverture.',
    expected_impact: 'Indexation de la page dans les 2–4 semaines. Récupération du trafic potentiel estimé à +120 clics/mois.',
    horizon: 'now',
    status: 'in_progress',
    visibility_impact: 4,
    business_impact: 4,
    effort: 1,
    confidence: 5,
    dependency_level: 1,
    priority_score: 9.2,
    owner: 'Tech SEO',
    created_at: '2025-07-11T09:00:00Z',
    updated_at: '2025-07-11T09:00:00Z',
  },
  {
    id: 'i2',
    workspace_id: 'ws1',
    opportunity_id: 'o3',
    type: 'quick_win',
    title: 'Optimiser titres et métas des pages blog sous-performantes',
    description: 'Réécrire les balises title et meta description des 5 pages blog avec CTR < 1.5%.',
    why_this_matters: 'Ces pages ont un fort volume d\'impressions mais un CTR très faible. Un titre plus attractif peut doubler les clics sans effort technique.',
    expected_impact: '+30 à +60% de CTR estimé sur les pages retravaillées, soit +200–400 clics/mois supplémentaires.',
    horizon: 'now',
    status: 'todo',
    visibility_impact: 3,
    business_impact: 3,
    effort: 1,
    confidence: 4,
    dependency_level: 1,
    priority_score: 8.1,
    owner: 'Content',
    created_at: '2025-07-10T10:00:00Z',
    updated_at: '2025-07-10T10:00:00Z',
  },
  {
    id: 'i3',
    workspace_id: 'ws1',
    opportunity_id: 'o2',
    type: 'core_fix',
    title: 'Corriger le maillage interne vers les 3 pages non indexées',
    description: 'Ajouter des liens internes pertinents depuis les pages à fort PageRank vers les 3 pages "Discovered but not indexed".',
    why_this_matters: 'Ces pages ne reçoivent aucun lien interne, ce qui explique qu\'elles soient découvertes mais non indexées. Le maillage est la solution la plus rapide.',
    expected_impact: 'Indexation attendue des 3 pages dans les 4–8 semaines après traitement.',
    horizon: 'now',
    status: 'todo',
    visibility_impact: 4,
    business_impact: 3,
    effort: 2,
    confidence: 4,
    dependency_level: 1,
    priority_score: 7.8,
    owner: 'Tech SEO',
    created_at: '2025-07-09T11:00:00Z',
    updated_at: '2025-07-09T11:00:00Z',
  },
  {
    id: 'i4',
    workspace_id: 'ws1',
    opportunity_id: 'o1',
    type: 'strategic',
    title: 'Créer le cluster contenu "nutrition senior chien"',
    description: 'Construire un hub de contenu autour du topic "nutrition chien senior" : page pilier + 4 à 6 articles satellites couvrant les sous-topics à volume.',
    why_this_matters: 'Le topic est entièrement non capté malgré un volume de 8 400 requêtes/mois. Les concurrents y sont déjà bien positionnés.',
    expected_impact: 'Potentiel de +500 à +1 200 clics/mois à 6 mois, avec une page pilier en top 5 sur 3 requêtes cibles.',
    horizon: 'next',
    status: 'todo',
    visibility_impact: 5,
    business_impact: 5,
    effort: 4,
    confidence: 3,
    dependency_level: 2,
    priority_score: 7.4,
    owner: 'Content',
    created_at: '2025-07-11T10:30:00Z',
    updated_at: '2025-07-11T10:30:00Z',
  },
  {
    id: 'i5',
    workspace_id: 'ws1',
    opportunity_id: 'o5',
    type: 'core_fix',
    title: 'Renforcer les pages produit sur les requêtes dominées par DogFood.be',
    description: 'Identifier les 5 pages concurrentes les plus performantes de DogFood.be et améliorer les pages correspondantes en termes de contenu, structure et UX.',
    why_this_matters: 'DogFood.be capte 78% du top 3 sur nos requêtes prioritaires. Sans contre-offensive ciblée, l\'écart va se creuser.',
    expected_impact: 'Récupération de 15–25% de positions perdues sur les requêtes ciblées dans les 3 mois.',
    horizon: 'next',
    status: 'todo',
    visibility_impact: 4,
    business_impact: 5,
    effort: 3,
    confidence: 3,
    dependency_level: 2,
    priority_score: 7.0,
    owner: 'SEO + Content',
    created_at: '2025-07-11T12:30:00Z',
    updated_at: '2025-07-11T12:30:00Z',
  },
  {
    id: 'i6',
    workspace_id: 'ws1',
    opportunity_id: 'o4',
    type: 'strategic',
    title: 'Produire du contenu E-E-A-T citatoire pour l\'AI Search',
    description: 'Créer 3 à 5 pages hautement structurées (données, études, avis expert) conçues pour être citées dans les AI Overviews.',
    why_this_matters: 'L\'absence totale dans les AI Overviews représente un risque de long terme car les AI-driven SERPs vont croître. Construire cette présence maintenant est un investissement stratégique.',
    expected_impact: 'Apparition en source dans 2–4 AI Overviews sur les requêtes cibles dans les 6 mois.',
    horizon: 'next',
    status: 'todo',
    visibility_impact: 4,
    business_impact: 4,
    effort: 4,
    confidence: 3,
    dependency_level: 3,
    priority_score: 6.5,
    owner: 'Content + SEO',
    created_at: '2025-07-11T15:30:00Z',
    updated_at: '2025-07-11T15:30:00Z',
  },
  {
    id: 'i7',
    workspace_id: 'ws1',
    opportunity_id: 'o1',
    type: 'strategic',
    title: 'Revamp section alimentation avec contenus experts',
    description: 'Refonte complète de la section /alimentation avec pages piliers révisées, contenu expert, données nutritionnelles vérifiées et FAQ structurée.',
    why_this_matters: 'La section alimentation est la moins performante du site malgré un fort volume de recherche. Une refonte structurelle peut en faire un levier majeur.',
    expected_impact: '+800 à +1 500 clics/mois après 9–12 mois, positionnement sur 8+ requêtes à volume.',
    horizon: 'later',
    status: 'todo',
    visibility_impact: 5,
    business_impact: 5,
    effort: 5,
    confidence: 3,
    dependency_level: 3,
    priority_score: 6.1,
    owner: 'Content',
    created_at: '2025-07-08T09:00:00Z',
    updated_at: '2025-07-08T09:00:00Z',
  },
  {
    id: 'i8',
    workspace_id: 'ws1',
    opportunity_id: 'o6',
    type: 'experiment',
    title: 'Test : Optimiser le Knowledge Panel via données structurées',
    description: 'Expérimenter l\'ajout de schema Organization, LocalBusiness et WebSite pour renforcer l\'entité marque dans les SERPs.',
    why_this_matters: 'La faible présence sur les requêtes navigationnelles peut être améliorée rapidement via des données structurées. Test à faible coût.',
    expected_impact: 'Amélioration de la recognition entité dans 4–8 semaines.',
    horizon: 'later',
    status: 'todo',
    visibility_impact: 3,
    business_impact: 3,
    effort: 2,
    confidence: 3,
    dependency_level: 1,
    priority_score: 5.8,
    owner: 'Tech SEO',
    created_at: '2025-07-09T14:00:00Z',
    updated_at: '2025-07-09T14:00:00Z',
  },
  {
    id: 'i9',
    workspace_id: 'ws1',
    opportunity_id: undefined,
    type: 'experiment',
    title: 'Pilote : Module GEO Questions',
    description: 'Tester la détection automatique de questions GEO liées au domaine et identifier les opportunités de réponse dans les AI Overviews.',
    why_this_matters: 'Le GEO (Generative Engine Optimization) est un nouveau front. Ce pilote permettra de construire une méthodologie interne avant que la concurrence ne s\'y mette.',
    expected_impact: 'Identification de 10–20 questions GEO à adresser en V2.',
    horizon: 'later',
    status: 'todo',
    visibility_impact: 3,
    business_impact: 3,
    effort: 4,
    confidence: 2,
    dependency_level: 2,
    priority_score: 4.5,
    owner: 'SEO Research',
    created_at: '2025-07-07T10:00:00Z',
    updated_at: '2025-07-07T10:00:00Z',
  },
]

export const mockGscTrend = [
  { date: '2025-06-14', clicks: 672, impressions: 12400 },
  { date: '2025-06-21', clicks: 695, impressions: 13100 },
  { date: '2025-06-28', clicks: 710, impressions: 13800 },
  { date: '2025-07-05', clicks: 642, impressions: 13200 },
  { date: '2025-07-12', clicks: 518, impressions: 12900 },
]
